### ISSUE TITLE
remove remaining bitwave references

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-livestream-player#1]
some CDN urls are still used - move to Odysee server / publish on Odysee. 

Odysee intro: https://cdn.lbryplayer.xyz/content/claims/odysee/7a416c44a6888d94fe045241bbac055c726332aa/stream.mp4 or https://cdn.lbryplayer.xyz/api/v4/streams/tc/odysee/7a416c44a6888d94fe045241bbac055c726332aa/a27e60ccaef16af441d76471f87d211a1791cc580d2b1dc333f81bab67dca8fa9bfea900bcf25da5a6585857240967b1/master.m3u8

Odysee streaming image placeholder: https://spee.ch/odysee-streaming-png:2.png?quality=80&height=630&width=1200

**Comment by DispatchCommit** [comment]
I created redirection rules to 302 redirect the current URL that does not load to the URLs provided and created a PR to modify the hard coded constants. If wanted, we could pull these URLs out to the .env file if so desired, however the existing PR just replaces the hardcoded locations.
